const switchBtn = document.querySelector('.btn')
console.log(switchBtn)
const label = document.querySelector('.inputLabel')
console.log(label)
const input = document.getElementById('inputW')
console.log(input)
